# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-netn=e

# This workflow will build and run a .NET project as a Windows service
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# name: Running Windows Service

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build-and-run:
#     runs-on: windows-latest

#     steps:
#     - uses: actions/checkout@v4
    
#     # Set up .NET environment
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: 8.0.x

#     # Restore dependencies
#     - name: Restore dependencies
#       run: dotnet restore

#     # Build the project
#     - name: Build
#       run: dotnet build --no-restore

#     # Publish the service to a specified output directory
#     - name: Publish Windows Service
#       run: dotnet publish --configuration Release --output ./publish

#     # Run the Windows Service application
#     - name: Run Windows Service
#       run: dotnet run --project "./filemonitoring1.csproj"
    
#     # Verify the service status (Optional Step)
#     - name: Verify Service Status
#       run: |
#         Write-Host "Service should be running now."
#         Write-Host "Ensure files are dynamically processed in 'SourceFolder1'."

name: Build, Publish, and Test Windows Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Publish Windows Service
        run: dotnet publish --configuration Release --output ./publish

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Create Test Folders and Files
        run: |
          mkdir -p $GITHUB_WORKSPACE/SourceFolder6
          mkdir -p $GITHUB_WORKSPACE/DestinationFolder6
          echo "This is a test file" > $GITHUB_WORKSPACE/SourceFolder6/testfile.txt

      - name: Start Windows Service
        run: |
          cd $GITHUB_WORKSPACE/windows_service/publish
          Start-Process -FilePath 'filemonitoring1.exe' -NoNewWindow -Wait

      - name: Wait for File Movement
        run: |
          echo "Waiting for file movement..."
          Start-Sleep -Seconds 20

      - name: Verify File Movement
        run: |
          $destinationPath = "$GITHUB_WORKSPACE/DestinationFolder6/testfile.txt"
          if (Test-Path -Path $destinationPath) {
            Write-Host "File moved successfully to DestinationFolder6."
          } else {
            Write-Error "File was not moved to DestinationFolder6."
          }
