# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-netn=e

name: Running Windows Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish Windows Service
      run: dotnet publish --configuration Release --output ./publish

    - name: Run Windows Service
      run: dotnet run --project "./filemonitoring1.csproj"  
 
    - name: Verify Service Status
      run: |
        Write-Host "Service should be running now."
